modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]] #mandatory
modId="spleaves"
version="${file.jarVersion}"
displayName="Spleaves"
logoFile="icon.png"
authors="UltrusBot"
description='''
Re-implements the spleaves from the 2023 April Fools Update, and adds some new features to them!
'''
[[dependencies.spleaves]] #optional
    modId="forge" #mandatory
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.spleaves]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
